# Generated by Django 6.0.2 on 2026-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='update image field', upload_to='categories/'),
            preserve_default=False,
        ),
    ]
